#JWT CONFIGURACAO
mp.jwt.verify.publickey.location=publicKey.pem 
mp.jwt.verify.issuer=https://loja.com/issuer
smallrye.jwt.sign.key.location=privateKey.pem 
smallrye.jwt.encrypt.key.location=publicKey.pem
quarkus.native.resources.includes=publicKey.pem 

#inicializa banco
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

#debug
%dev.quarkus.log.category."io.quarkus.smallrye.jwt".level=DEBUG
%dev.quarkus.log.category."io.smallrye.jwt".level=DEBUG